language: python
dist: xenial
env:
    global:
        - SKIP_GENERATE_AUTHORS=1
        - SKIP_WRITE_GIT_CHANGELOG=1
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"
install:
    - pip install -U pip
    - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then pip install pathlib2; fi
    - pip install .[test]
script:
    - py.test -v tests
deploy:
    provider: pypi
    user: jbarnoud
    password:
        secure: "B3e32jJDd3N57d1hwULBf5Kcyns8X9uL76GVSRLZK4Bq6K1MnnuUcPLWFCEfqMeXU3sYprPq0MIO/CrUtyqp4dumTbj0+AxrEksxRBaAMRN2H8nCtgQSm5U2caGT27pIq0FEHmMwJRB49jL2LNdi73m/ey7aSzydjrfOt3/KVNjHYDPq0f30YZQyYWh/LNC/Cd0O6ZYfz5LGvgXp+tqSObkr/T9jvOP2d8rTWW69GX6rf+k+tspDVMHCLhVSVgirXPvmoKY5gG5NsPC2ECrNXi5RbAu7nFcY8XPYvMOZzXVQqOIPBEuDrUS2fxd7f0t5+RHZG/XLBbDF3g1Xi6U7OMtr5JkCzFTUzgWLa8Pu98i6w5bfTgn2Y+iYECkJf/UpwF25iQFJBC8jhI6wHzEhWVjnidlyWTf2H4I7cLS+Nu4mWbagkJEbYGUUGwx1A5TKt+U7Y9KJJGuHk5UEwIE0uEPvzu9b2Kiqf+4orF7ukrYG8PJVz4ZNDpT6QB7JmFy3zw8zRjvQ/E7xlBEth5+hhb4l2gf0P6yN8sw9478URYRtr7S37vbQ/UcQ7yv7nTmzb51f3JgdsSGCSfWpnxKTjyp90WBKJTzTOm2twFgRUKlvvUtThKcwSpAPKn451rGGhM7o5LXBw/wumcve3Yr9KmBM2kXYdQQuibT8o1xSZAY="
    distributions: sdist bdist_wheel
    skip_existing: true
